### ISSUE TITLE
PHP sample code uses sha1, but default skin is sha256 now

### ISSUE THREAD

**Issue by stembrain** [Adyen/php#9]
So the merchant signature comes out wrong

Workarounds:
Switch the php sample code to use sha256
OR
Switch the skin to sha1 (which doesn't have a clean workflow in the CA)

**Comment by HugoTrimp** [comment]
The new HMAC-SHA256 signing needs to be calculated in a different way. Please find a PHP code example on https://docs.adyen.com/pages/viewpage.action?pageId=5376964
